### ISSUE TITLE
Player walking off the platform

### ISSUE THREAD

**Issue by Aphixr** [JonathanW2018/Three#1]
If you leave the player where it spawned, you can make the player walk off the platform by holding the down and right keys. Releasing the down key (but not the right key) will teleport the player back onto the platform.\
\
Edit: you can do the same to the other corners of the map too.

**Comment by Encryptium** [comment]
Thanks! Just realized that this can happen on any corner. The problem will be fixed soon.

**Comment by JonathanW2018** [comment]
.

**Comment by Encryptium** [comment]
Issue fixed in version [2021.7.8](https://github.com/JonathanW2018/Three/releases/tag/2021.7.8). 
If you want to see your contribution that helped make the game better, try installing the new version.

**Note:** This update will not be available through the included updater in each version. But future versions will.
